import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../core/theme/app_colors.dart';
import '../../core/theme/app_text_styles.dart';
import '../../shared/services/voice_service.dart';

/// The final localized risk assessment card generated by the AI Screening endpoint.
/// Visually designed specifically for rural legibility and direct calls to action.
class HealthSignalCard extends StatefulWidget {
  final String riskLevel;        // "GREEN", "YELLOW", "RED"
  final List<String> symptoms;   // Array of identified clinical terms in Tamil
  final String aiReason;         // Core explanation logic
  final String hospitalPhrase;   // Pre-filled Tamil phrase to speak to doctor

  const HealthSignalCard({
    super.key,
    required this.riskLevel,
    required this.symptoms,
    required this.aiReason,
    this.hospitalPhrase = "",
  });

  @override
  State<HealthSignalCard> createState() => _HealthSignalCardState();
}

class _HealthSignalCardState extends State<HealthSignalCard> {
  @override
  void initState() {
    super.initState();
    // Auto-read the card upon rendering
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _announceCard();
    });
  }

  Future<void> _announceCard() async {
    final voice = context.read<VoiceService>();
    final level = widget.riskLevel.toUpperCase();
    
    // Explicit dynamic reads matching visual constraints
    String prefix = "";
    if (level == "GREEN") prefix = "நீங்கள் நலமாக இருக்கீங்க. ";
    if (level == "YELLOW") prefix = "கவனிக்க வேண்டும். ";
    if (level == "RED") prefix = "அவசரம்! உடனடியாக மருத்துவமனை போங்க. ";
    
    await voice.speak("$prefix ${widget.aiReason}");
  }

  Future<void> _callAmbulance() async {
    final Uri url = Uri.parse('tel:108');
    if (await canLaunchUrl(url)) {
      await launchUrl(url);
    } else {
      context.read<VoiceService>().speak("மன்னிக்கவும், அழைக்க முடியவில்லை. 108 ஐ நேரடியாக டயல் செய்யவும்.");
    }
  }

  Future<void> _shareReport() async {
    final level = widget.riskLevel.toUpperCase();
    String report = "*வணக்கம் அக்கா - உடல்நல அறிக்கை (Health Report)*\n\n";
    
    if (level == "GREEN") report += "✅ *நிலைமை: பாதுகாப்பானது (GREEN)*\n";
    if (level == "YELLOW") report += "⚠️ *நிலைமை: கவனம் தேவை (YELLOW)*\n";
    if (level == "RED") report += "🚨 *நிலைமை: அவசரம் (RED)*\n";
    
    report += "\n*அறிகுறிகள்:*\n";
    for (var s in widget.symptoms) {
      report += "• $s\n";
    }
    
    report += "\n*காரணம்:*\n${widget.aiReason}\n";
    
    if (widget.hospitalPhrase.isNotEmpty && level != "GREEN") {
      report += "\n*மருத்துவரிடம் சொல்ல வேண்டியது:*\n\"${widget.hospitalPhrase}\"";
    }

    Share.share(report);
  }

  @override
  Widget build(BuildContext context) {
    if (widget.riskLevel.toUpperCase() == "GREEN") return _buildGreenCard();
    if (widget.riskLevel.toUpperCase() == "YELLOW") return _buildYellowCard();
    if (widget.riskLevel.toUpperCase() == "RED") return _buildRedCard();
    
    return const SizedBox.shrink(); // Safety fallback
  }

  // =====================================
  //  GREEN CARD - SAFE / MILD
  // =====================================
  Widget _buildGreenCard() {
    return _buildBaseCard(
      backgroundColor: const Color(0xFFE8F5E9), // Light green
      borderColor: AppColors.riskGreen,
      icon: Icons.check_circle_rounded,
      title: "நீங்கள் நலமாக இருக்கீங்க",
      titleColor: AppColors.riskGreen,
      actionButtons: [
        _buildActionButton(
          label: "ரிமைண்டர் வைக்கவும்", 
          icon: Icons.notifications_active_rounded,
          color: AppColors.riskGreen,
          onTap: () {
            context.read<VoiceService>().speak("நினைவூட்டல் சேமிக்கப்பட்டது");
          }
        )
      ],
      advice: "7 நாளுக்கு பிறகு மீண்டும் பரிசோதிக்கவும்",
    );
  }

  // =====================================
  //  YELLOW CARD - WARNING / PHC
  // =====================================
  Widget _buildYellowCard() {
    return _buildBaseCard(
      backgroundColor: const Color(0xFFFFF8E1), // Warm amber background
      borderColor: AppColors.riskYellow,
      icon: Icons.warning_rounded,
      title: "கவனிக்க வேண்டும்",
      titleColor: AppColors.riskYellow,
      advice: "3 நாளுக்குள் அரசு ஆரம்ப சுகாதார நிலையத்திற்கு (PHC) செல்லவும்",
      showDoctorPhrase: true,
      actionButtons: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Expanded(
              child: _buildActionButton(
                label: "PHC எங்கே?", 
                icon: Icons.local_hospital_rounded,
                color: AppColors.riskYellow,
                onTap: () {
                  context.read<VoiceService>().speak("வரைபடம் திறக்கப்படுகிறது"); // Opening map
                }
              ),
            ),
            const SizedBox(width: 8),
            Expanded(
              child: _buildActionButton(
                label: "நர்ஸிடம் பேசு", 
                icon: Icons.person_rounded,
                color: AppColors.riskYellow,
                onTap: () {} // Ties to consultation features later
              ),
            ),
          ],
        )
      ],
    );
  }

  // =====================================
  //  RED CARD - EMERGENCY / 108
  // =====================================
  Widget _buildRedCard() {
    return _buildBaseCard(
      backgroundColor: const Color(0xFFFFEBEE), // Light red alert background
      borderColor: AppColors.riskRed,
      icon: Icons.error_rounded,
      title: "உடனடியாக மருத்துவமனை போங்க",
      titleColor: AppColors.riskRed,
      advice: "உடனடி சிகிச்சை கட்டாயம் தேவை. உங்கள் VHN-க்கு தகவல் அனுப்பப்பட்டுள்ளது.", // Urgent care required. VHN notified.
      showDoctorPhrase: true,
      actionButtons: [
        // Massive 108 Call to Action Button
        SizedBox(
          width: double.infinity,
          height: 64, // Extra large for panic scenarios
          child: ElevatedButton.icon(
            style: ElevatedButton.styleFrom(
              backgroundColor: AppColors.riskRed,
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16))
            ),
            icon: const Icon(Icons.phone_in_talk_rounded, size: 32),
            label: Text("அம்புலன்ஸ்: 108", style: AppTextStyles.headingLarge.copyWith(color: Colors.white)),
            onPressed: () {
              context.read<VoiceService>().speak("ஆம்புலன்ஸை அழைக்கிறேன்");
              _callAmbulance();
            },
          ),
        ),
        const SizedBox(height: 12),
        // Secondary Emergency options
        _buildActionButton(
          label: "அருகில் உள்ள அரசு மருத்துவமனை", 
          icon: Icons.map_rounded,
          color: AppColors.riskRed,
          onTap: () {}
        )
      ],
    );
  }

  // =====================================
  //  BASE ARCHITECTURE DESIGN LAYER
  // =====================================
  Widget _buildBaseCard({
    required Color backgroundColor,
    required Color borderColor,
    required IconData icon,
    required String title,
    required Color titleColor,
    required String advice,
    required List<Widget> actionButtons,
    bool showDoctorPhrase = false,
  }) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 24),
      decoration: BoxDecoration(
        color: backgroundColor,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: borderColor.withValues(alpha: 0.5), width: 2),
        boxShadow: [
          BoxShadow(
            color: borderColor.withValues(alpha: 0.15),
            blurRadius: 16,
            spreadRadius: 4,
            offset: const Offset(0, 8)
          )
        ]
      ),
      child: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          mainAxisSize: MainAxisSize.min,
          children: [
            // Banner Headers
            Row(
              children: [
                Icon(icon, color: titleColor, size: 48),
                const SizedBox(width: 16),
                Expanded(
                  child: Text(title, style: AppTextStyles.headingMedium.copyWith(color: titleColor)),
                )
              ],
            ),
            
            const SizedBox(height: 24),
            
            // Jargon-free Explanation
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(16)),
              child: Text(widget.aiReason, style: AppTextStyles.bodyLarge),
            ),
            
            const SizedBox(height: 16),

            // Discovered Symptom bullets
            if (widget.symptoms.isNotEmpty)
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text("அறிகுறிகள் (Symptoms):", style: AppTextStyles.bodyLarge.copyWith(fontWeight: FontWeight.bold)),
                  const SizedBox(height: 8),
                  ...widget.symptoms.map((s) => Padding(
                    padding: const EdgeInsets.only(bottom: 4),
                    child: Row(
                      children: [
                        Icon(Icons.circle, size: 8, color: borderColor),
                        const SizedBox(width: 12),
                        Text(s, style: AppTextStyles.bodyLarge),
                      ],
                    ),
                  )),
                ],
              ),
              
            const SizedBox(height: 16),

            // Pre-filled Doctor Advice snippet
            if (showDoctorPhrase && widget.hospitalPhrase.isNotEmpty)
               Container(
                 padding: const EdgeInsets.all(16),
                 decoration: BoxDecoration(
                   color: AppColors.surface,
                   border: Border(left: BorderSide(color: titleColor, width: 4)),
                 ),
                 child: Column(
                   crossAxisAlignment: CrossAxisAlignment.start,
                   children: [
                     Text("மருத்துவரிடம் சொல்ல வேண்டியது:", style: AppTextStyles.bodySmall.copyWith(fontWeight: FontWeight.bold, color: AppColors.textSecondary)),
                     const SizedBox(height: 8),
                     Text('"${widget.hospitalPhrase}"', style: AppTextStyles.bodyLarge.copyWith(fontStyle: FontStyle.italic)),
                   ],
                 ),
               ),

            const SizedBox(height: 24),
            
            // Required Action & Advice
            Center(
              child: Text(advice, style: AppTextStyles.headingMedium.copyWith(color: titleColor), textAlign: TextAlign.center),
            ),
            
            const SizedBox(height: 24),
            const Divider(),
            const SizedBox(height: 16),
            
            ...actionButtons,

            const SizedBox(height: 16),

            // Global Card Action Toolbar
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                TextButton.icon(
                  onPressed: _shareReport,
                  icon: const Icon(Icons.share_rounded),
                  label: const Text("பகிர்க (Share)"),
                ),
                TextButton.icon(
                  onPressed: () {
                     context.read<VoiceService>().speak("குறிப்பேட்டில் சேமிக்கப்பட்டது"); // Saved to notebook
                  },
                  icon: const Icon(Icons.save_rounded),
                  label: const Text("சேமி (Save)"),
                ),
              ],
            )
          ],
        ),
      ),
    );
  }

  Widget _buildActionButton({required String label, required IconData icon, required Color color, required VoidCallback onTap}) {
    return ElevatedButton.icon(
      style: ElevatedButton.styleFrom(
        backgroundColor: color,
        foregroundColor: Colors.white,
        padding: const EdgeInsets.symmetric(vertical: 12),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))
      ),
      icon: Icon(icon),
      label: Text(label, style: AppTextStyles.bodyLarge.copyWith(color: Colors.white, fontWeight: FontWeight.bold)),
      onPressed: onTap,
    );
  }
}
